spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration-seconds: ${APP_JWT_EXPIRATION_SECONDS:7200}
