@baseUrl = http://localhost:8081

### 注册成功
POST {{baseUrl}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "ocean_user_001",
  "password": "Ocean1234",
  "nickname": "海洋爱好者",
  "email": "ocean001@example.com",
  "phone": "13800000001"
}

### 重复注册
POST {{baseUrl}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "ocean_user_001",
  "password": "Ocean1234",
  "nickname": "重复用户",
  "email": "ocean001@example.com",
  "phone": "13800000001"
}

### 注册参数不合法
POST {{baseUrl}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "ab",
  "password": "123",
  "email": "错误邮箱"
}

### 登录成功
POST {{baseUrl}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "ocean_user_001",
  "password": "Ocean1234"
}

> {%
    client.global.set(
        "accessToken",
        response.body.data.accessToken
    );
%}

### 查询当前登录用户
GET {{baseUrl}}/api/users/me
Accept: application/json
Authorization: Bearer {{accessToken}}

### 登录密码错误
POST {{baseUrl}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "ocean_user_001",
  "password": "WrongPassword"
}
