<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { UploadFilled, Clock, SuccessFilled, WarningFilled } from '@element-plus/icons-vue'; import { ElMessage } from 'element-plus'; import { detectFishApi, listDetectionRecordsApi } from '../api/detection'; import type { DetectionRecord } from '../types/business'
const file = ref<File | null>(null); const preview = ref(''); const confidence = ref(0.5); const detecting = ref(false); const current = ref<DetectionRecord | null>(null); const records = ref<DetectionRecord[]>([])
function selectFile(uploadFile: { raw?: File }) { if (!uploadFile.raw) return; file.value = uploadFile.raw; if (preview.value) URL.revokeObjectURL(preview.value); preview.value = URL.createObjectURL(uploadFile.raw) }
async function detect() { if (!file.value) return ElMessage.warning('请先选择一张鱼类图片'); detecting.value = true; try { const { data } = await detectFishApi(file.value, confidence.value); current.value = data.data; ElMessage.success('识别任务已完成'); loadRecords() } finally { detecting.value = false } }
async function loadRecords() { const { data } = await listDetectionRecordsApi(); records.value = data.data.records } onMounted(loadRecords)
function statusText(status: string) { return ({ SUCCESS: '识别成功', FAILED: '识别失败', NO_TARGET: '未发现目标', PROCESSING: '处理中' } as Record<string,string>)[status] || status }
</script>
<template><section class="page-hero compact"><div class="page-container"><p class="eyebrow">AI FISH RECOGNITION</p><h1>智能识别实验室</h1><p>上传图片，系统会保存原图、识别结果、置信度和失败原因。</p></div></section><section class="business-page page-container"><div class="detection-grid"><div class="upload-workbench"><h2>上传待识别图片</h2><el-upload drag :auto-upload="false" :show-file-list="false" accept="image/jpeg,image/png,image/webp" :on-change="selectFile"><img v-if="preview" class="preview-image" :src="preview" alt="待识别预览"><template v-else><el-icon class="el-icon--upload"><UploadFilled /></el-icon><div>拖拽图片到这里，或点击选择</div><small>支持 JPG、PNG、WebP，最大 10MB</small></template></el-upload><label>最低置信度 {{ Math.round(confidence * 100) }}%</label><el-slider v-model="confidence" :min="0.1" :max="0.95" :step="0.05" /><el-button type="primary" size="large" :loading="detecting" @click="detect">开始智能识别</el-button></div><div class="result-panel"><h2>本次识别结果</h2><el-empty v-if="!current" description="上传图片后，结果会显示在这里" /><template v-else><div class="result-status"><el-icon v-if="current.status === 'SUCCESS'"><SuccessFilled /></el-icon><el-icon v-else><WarningFilled /></el-icon><div><strong>{{ statusText(current.status) }}</strong><span>耗时 {{ current.durationMs || 0 }} ms · {{ current.modelName }}</span></div></div><p v-if="current.errorMessage" class="error-note">{{ current.errorMessage }}</p><article v-for="result in current.results" :key="result.id" class="detect-result"><div><h3>{{ result.chineseName || result.className }}</h3><em>{{ result.scientificName || '资料库暂未收录' }}</em></div><strong>{{ Math.round(Number(result.confidence) * 100) }}%</strong><p>{{ result.category || '分类待补充' }} · {{ result.habitat || '栖息地待补充' }}</p><el-tag v-if="result.fishProfileMissing" type="warning">已反馈管理员补充资料</el-tag></article></template></div></div><div class="history-panel"><h2>我的识别记录</h2><div class="history-list"><article v-for="record in records" :key="record.id" @click="current = record"><el-icon><Clock /></el-icon><div><strong>{{ record.originalFileName }}</strong><span>{{ record.createdAt?.replace('T',' ').slice(0,16) }}</span></div><el-tag :type="record.status === 'SUCCESS' ? 'success' : 'info'">{{ statusText(record.status) }}</el-tag></article><el-empty v-if="records.length === 0" description="暂无识别记录" /></div></div></section></template>
