<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { ElMessage } from 'element-plus'; import type { FormInstance, FormRules } from 'element-plus'; import { useAuthStore } from '../stores/auth'
const auth = useAuthStore(); const formRef = ref<FormInstance>(); const saving = ref(false); const form = reactive({ nickname: '', email: '', phone: '', avatarUrl: '' })
const rules: FormRules = { email: [{ type: 'email', message: '邮箱格式不正确', trigger: 'blur' }], phone: [{ pattern: /^$|^1\d{10}$/, message: '手机号格式不正确', trigger: 'blur' }] }
function fillForm() { form.nickname = auth.user?.nickname || ''; form.email = auth.user?.email || ''; form.phone = auth.user?.phone || ''; form.avatarUrl = auth.user?.avatarUrl || '' }
onMounted(async () => { await auth.refreshCurrentUser(); fillForm() })
async function save() { if (!await formRef.value?.validate()) return; saving.value = true; try { await auth.updateProfile(form); ElMessage.success('个人资料已更新') } finally { saving.value = false } }
</script>
<template><section class="profile-page page-container"><div class="profile-heading"><div class="avatar">{{ auth.displayName.slice(0, 1) }}</div><div><p class="eyebrow dark">PERSONAL CENTER</p><h1>{{ auth.displayName }}</h1><p>@{{ auth.user?.username }}</p></div><div class="role-tags"><el-tag v-for="role in auth.roles" :key="role" effect="dark">{{ role }}</el-tag></div></div><div class="profile-grid"><aside><h3>账号概览</h3><dl><div><dt>账号状态</dt><dd>{{ auth.user?.status === 'ACTIVE' ? '正常使用' : '已停用' }}</dd></div><div><dt>用户编号</dt><dd>#{{ auth.user?.id }}</dd></div><div><dt>注册时间</dt><dd>{{ auth.user?.createdAt?.slice(0, 10) }}</dd></div></dl><p>角色由后台权限表控制。普通用户通过申请并经管理员审核后，可以增加 VOLUNTEER 角色。</p></aside><section class="profile-form"><h2>编辑个人资料</h2><el-form ref="formRef" :model="form" :rules="rules" label-position="top" @submit.prevent="save"><el-form-item label="昵称"><el-input v-model="form.nickname" size="large" /></el-form-item><el-form-item label="邮箱" prop="email"><el-input v-model="form.email" size="large" /></el-form-item><el-form-item label="手机号码" prop="phone"><el-input v-model="form.phone" size="large" /></el-form-item><el-form-item label="头像地址"><el-input v-model="form.avatarUrl" size="large" /></el-form-item><el-button type="primary" size="large" native-type="submit" :loading="saving">保存修改</el-button></el-form></section></div></section></template>
