<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { ElMessage } from 'element-plus'; import { Location, Plus } from '@element-plus/icons-vue'; import { createRescueApi, listMyRescuesApi, listPublicRescuesApi } from '../api/rescue'; import { useAuthStore } from '../stores/auth'; import type { RescueOrder } from '../types/business'
const auth = useAuthStore(); const publicOrders = ref<RescueOrder[]>([]); const myOrders = ref<RescueOrder[]>([]); const dialog = ref(false); const submitting = ref(false); const form = reactive({ issueType: 'INJURED_ANIMAL', title: '', description: '', locationText: '', latitude: undefined as number|undefined, longitude: undefined as number|undefined, imageText: '' })
const statusMap: Record<string,string> = { PENDING_REVIEW:'待审核',OPEN:'等待志愿者',ACCEPTED:'处理中',COMPLETION_PENDING:'等待验收',COMPLETED:'已完成',REJECTED:'未通过' }
async function load() { const { data } = await listPublicRescuesApi(); publicOrders.value = data.data.records; if (auth.isLoggedIn) { const mine = await listMyRescuesApi(); myOrders.value = mine.data.data.records } }
function locate() { navigator.geolocation?.getCurrentPosition((pos)=>{ form.latitude=Number(pos.coords.latitude.toFixed(7)); form.longitude=Number(pos.coords.longitude.toFixed(7)); ElMessage.success('已获取浏览器坐标') },()=>ElMessage.warning('无法获取位置，请手动填写')) }
async function submit() { submitting.value=true; try { await createRescueApi({ ...form, imageUrls: form.imageText.split('\n').map(v=>v.trim()).filter(Boolean) }); ElMessage.success('工单已提交，等待管理员审核'); dialog.value=false; Object.assign(form,{issueType:'INJURED_ANIMAL',title:'',description:'',locationText:'',latitude:undefined,longitude:undefined,imageText:''}); load() } finally { submitting.value=false } }
onMounted(load)
</script>
<template><section class="page-hero compact"><div class="page-container"><p class="eyebrow">MARINE RESCUE NETWORK</p><h1>公益救助大厅</h1><p>查看已公开的环境和动物救助信息，让每一次处理过程都能被追踪。</p></div></section><section class="business-page page-container"><div class="business-toolbar"><div><h2>公开救助公告</h2><p>只有管理员审核通过的工单才会在这里显示。</p></div><el-button v-if="auth.isLoggedIn" type="primary" :icon="Plus" @click="dialog=true">上报问题</el-button><RouterLink v-else class="primary-link" to="/login">登录后上报</RouterLink></div><div class="rescue-grid"><article v-for="order in publicOrders" :key="order.id"><div class="rescue-card-top"><el-tag>{{ order.issueType === 'INJURED_ANIMAL' ? '受伤动物' : order.issueType === 'ENVIRONMENT' ? '环境问题' : '其他问题' }}</el-tag><span>{{ statusMap[order.status] || order.status }}</span></div><h3>{{ order.title }}</h3><p>{{ order.description }}</p><div><el-icon><Location /></el-icon>{{ order.locationText || '位置未填写' }}</div></article><el-empty v-if="publicOrders.length===0" description="目前没有公开救助公告" /></div><template v-if="auth.isLoggedIn"><div class="business-toolbar sub"><div><h2>我的上报记录</h2><p>可以查看审核意见和当前处理状态。</p></div></div><el-table :data="myOrders" stripe><el-table-column prop="title" label="工单标题" min-width="220"/><el-table-column prop="issueType" label="类型"/><el-table-column prop="status" label="状态"><template #default="scope"><el-tag>{{ statusMap[scope.row.status] || scope.row.status }}</el-tag></template></el-table-column><el-table-column prop="reviewComment" label="审核意见" min-width="180"/></el-table></template></section><el-dialog v-model="dialog" title="上报海洋救助问题" width="min(620px, 92vw)"><el-form :model="form" label-position="top"><el-form-item label="问题类型"><el-select v-model="form.issueType" style="width:100%"><el-option label="受伤动物" value="INJURED_ANIMAL"/><el-option label="环境问题" value="ENVIRONMENT"/><el-option label="其他问题" value="OTHER"/></el-select></el-form-item><el-form-item label="工单标题"><el-input v-model="form.title" maxlength="150"/></el-form-item><el-form-item label="详细描述"><el-input v-model="form.description" type="textarea" :rows="5" maxlength="5000" show-word-limit/></el-form-item><el-form-item label="位置描述"><el-input v-model="form.locationText"><template #append><el-button @click="locate">获取坐标</el-button></template></el-input></el-form-item><div class="form-row"><el-form-item label="纬度"><el-input-number v-model="form.latitude" :min="-90" :max="90" :precision="7"/></el-form-item><el-form-item label="经度"><el-input-number v-model="form.longitude" :min="-180" :max="180" :precision="7"/></el-form-item></div><el-form-item label="图片地址（每行一个，最多 9 个）"><el-input v-model="form.imageText" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="submitting" @click="submit">确认提交</el-button></template></el-dialog></template>
