<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { ElMessage, ElMessageBox } from 'element-plus'; import { acceptRescueApi, completeRescueApi, createVolunteerApplicationApi, listMyVolunteerApplicationsApi, listPublicRescuesApi, listVolunteerOrdersApi } from '../api/rescue'; import { useAuthStore } from '../stores/auth'; import type { RescueOrder, VolunteerApplication } from '../types/business'
const auth=useAuthStore(); const applications=ref<VolunteerApplication[]>([]); const openOrders=ref<RescueOrder[]>([]); const myOrders=ref<RescueOrder[]>([]); const applying=ref(false); const form=reactive({realName:'',phone:'',region:'',skills:'',reason:''})
const statusMap:Record<string,string>={PENDING:'审核中',APPROVED:'已通过',REJECTED:'未通过',OPEN:'可接单',ACCEPTED:'处理中',COMPLETION_PENDING:'等待管理员验收',COMPLETED:'已完成'}
async function load(){ applications.value=(await listMyVolunteerApplicationsApi()).data.data; if(auth.isVolunteer){ openOrders.value=(await listPublicRescuesApi()).data.data.records.filter(v=>v.status==='OPEN'); myOrders.value=(await listVolunteerOrdersApi()).data.data.records } }
async function apply(){ applying.value=true;try{await createVolunteerApplicationApi(form);ElMessage.success('志愿者申请已提交');Object.assign(form,{realName:'',phone:'',region:'',skills:'',reason:''});load()}finally{applying.value=false}}
async function accept(id:number){await ElMessageBox.confirm('确认接取这条救助工单吗？','接单确认');await acceptRescueApi(id);ElMessage.success('接单成功');load()}
async function complete(id:number){const {value}=await ElMessageBox.prompt('请填写完成情况，管理员验收后工单才会结束。','提交处理反馈',{inputType:'textarea',inputValidator:(v)=>v?.trim()?true:'完成说明不能为空'});await completeRescueApi(id,value);ElMessage.success('已提交管理员验收');load()}
onMounted(load)
</script>
<template><section class="page-hero compact"><div class="page-container"><p class="eyebrow">VOLUNTEER ACTION</p><h1>志愿者中心</h1><p>申请志愿者身份，接取公开救助工单，并反馈现场处理结果。</p></div></section><section class="business-page page-container"><template v-if="!auth.isVolunteer"><div class="volunteer-apply"><div><p class="eyebrow dark">BECOME A VOLUNTEER</p><h2>申请成为海洋志愿者</h2><p>管理员审核通过后，系统会给当前账号增加 VOLUNTEER 角色。它不会删除原来的 USER 角色。</p><div v-for="item in applications" :key="item.id" class="application-record"><strong>{{ item.realName }}</strong><el-tag>{{ statusMap[item.status] || item.status }}</el-tag><span>{{ item.reviewComment || '等待管理员审核' }}</span></div></div><el-form :model="form" label-position="top"><div class="form-row"><el-form-item label="真实姓名"><el-input v-model="form.realName"/></el-form-item><el-form-item label="联系电话"><el-input v-model="form.phone"/></el-form-item></div><el-form-item label="所在地区"><el-input v-model="form.region"/></el-form-item><el-form-item label="擅长领域"><el-input v-model="form.skills" placeholder="例如：潜水、动物护理、摄影、运输"/></el-form-item><el-form-item label="申请理由"><el-input v-model="form.reason" type="textarea" :rows="5"/></el-form-item><el-button type="primary" size="large" :loading="applying" @click="apply">提交志愿者申请</el-button></el-form></div></template><template v-else><div class="business-toolbar"><div><h2>等待接取的工单</h2><p>接单后只有你可以提交这条工单的完成反馈。</p></div></div><div class="rescue-grid"><article v-for="order in openOrders" :key="order.id"><el-tag>可接单</el-tag><h3>{{ order.title }}</h3><p>{{ order.description }}</p><el-button type="primary" @click="accept(order.id)">接取工单</el-button></article><el-empty v-if="openOrders.length===0" description="目前没有待接取工单"/></div><div class="business-toolbar sub"><div><h2>我负责的工单</h2><p>完成现场处理后提交说明，由管理员进行最终验收。</p></div></div><el-table :data="myOrders" stripe><el-table-column prop="title" label="工单" min-width="200"/><el-table-column prop="locationText" label="位置"/><el-table-column prop="status" label="状态"><template #default="scope"><el-tag>{{statusMap[scope.row.status]||scope.row.status}}</el-tag></template></el-table-column><el-table-column label="操作"><template #default="scope"><el-button v-if="scope.row.status==='ACCEPTED'" type="primary" link @click="complete(scope.row.id)">提交完成反馈</el-button><span v-else>{{scope.row.completionDescription||'暂无操作'}}</span></template></el-table-column></el-table></template></section></template>
